Revert "Comment out osg34-stashcache.yaml instead of moving it to root"
This reverts commit 4205fe2127aeefe626ecf204ab16d9dad9af0298.

Having a completely commented-out yaml file kills the run with
```
Traceback (most recent call last):
  File "/osgtest/runs/run-20190409-1657/generate-dag", line 82, in <module>
    run_params = vmu.load_run_params(param_dir)
  File "/osgtest/runs/run-20190409-1657/vmu.py", line 36, in load_run_params
    if set(param_contents) == set(['platforms', 'sources', 'package_sets']):
TypeError: 'NoneType' object is not iterable
```